- id: scieqlint
  name: SciEqLint
  description: Check equations and equation references in supported scientific documents.
  entry: python -P -m scieqlint.pre_commit
  args: ["--"]
  language: python
  stages: [pre-commit]
  minimum_pre_commit_version: "3.2.0"
  always_run: true
  pass_filenames: false
