- id: scieqlint
  name: SciEqLint
  description: Check equations and equation references in supported scientific documents.
  entry: scieqlint check
  args: ["--"]
  language: python
  files: '(?i)\.(md|markdown|tex|ipynb)$'
  pass_filenames: false
  require_serial: true
